files:
  - source: /po/mmex.pot
    translation: /po/%locale_with_underscore%.po
    languages_mapping:
        locale_with_underscore:
             "sr_SP": "sr"
             "sr-SP": "sr"
        language:
            "sr_SP": "sr"
            "sr-SP": "sr"
    translation_replace: {"_SP" : ""}
