files:
  - source: /po/mmex.pot
    translation: /po/%locale_with_underscore%.po
    languages_mapping:
        locale_with_underscore:
            sr: sr_SP
            ru_RU: ru
    language:
        sr: sr_SP
        ru_RU: ru
    translation_replace: {"_SP" : ""}
