files:
  - source: /po/mmex.pot
    translation: /po/%locale_with_underscore%.po
    language: {"sr_SP": "sr"}
    languages_mapping:
        locale_with_underscore: {"sr_SP": "sr"}
    translation_replace: {"_SP" : ""}
